name: ece448
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.15
  - matplotlib
  - nltk>=3.4
  - tqdm>=4.24.0
  - scikit-learn >= 0.22
  - pytorch
  - ipykernel
  - pip:
    - gradescope-utils>=0.2.7